import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'

const payload = {
    "e": "24hrMiniTicker",  // Event type
    "E": 123456789,         // Event time
    "s": "BNBBTC",          // Symbol
    "c": "0.0025",          // Close price
    "o": "0.0010",          // Open price
    "h": "0.0025",          // High price
    "l": "0.0010",          // Low price
    "v": "10000",           // Total traded base asset volume
    "q": "18"               // Total traded quote asset volume
}

export default function Home() {
    const [price, setPrice] = useState({ ask: "", bid: "" })

    const onMessageHandler = (e: { data: string }) => {
        const data = JSON.parse(e.data)
        const ask = parseFloat(data.a).toFixed(2)
        const bid = parseFloat(data.b).toFixed(2)

        setPrice({ ask, bid })
    }

    useEffect(() => {
        const ws = new WebSocket("wss://stream.binance.com:9443/ws/btcusdt@bookTicker")
        ws.onmessage = onMessageHandler
        return () => ws.close()
    }, [])

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <p>ask = {price.ask}  bid = {price.bid}</p>
        </div>
    )
}
